name: BuildDocuments
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    
    steps:
        
    - name: install git
      run: apk add --update git 
        
    - name: install asciidoctor requirements
      run: |
       apk add graphicsmagick-dev ruby-dev musl-dev gcc
       gem install asciidoctor-bibtex asciidoctor-mathematical prawn-gmagick
      
    - name: checkout 
      uses: actions/checkout@master

    - name: build SONARnetCDF4 html
      run: asciidoctor -r asciidoctor-bibtex -r asciidoctor-mathematical --backend html5 -a data-uri -a mathematical-format=svg crr341.adoc
      working-directory: docs
    
    - name: build SONARnetCDF4 pdf
      run: asciidoctor-pdf -r asciidoctor-bibtex -r asciidoctor-mathematical crr341.adoc
      working-directory: docs
    
    - name: move crr341 files to report folder
      run: |
        mkdir -p Formatted_docs
        mv docs/crr341.html Formatted_docs/
        mv docs/crr341.pdf Formatted_docs/
        
    - name: Git stuff
      run: |
        git config --global --add safe.directory $PWD
        git config --local user.email "github@ices.dk"
        git config --local user.name "ices-github-bot"
        git status
        git add Formatted_docs/crr341.html
        git add -f Formatted_docs/crr341.pdf
        git commit --allow-empty -m "Push triggered asciidoc build"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
